### ISSUE TITLE
wanted to know more about this repo

### ISSUE THREAD

**Issue by NirmalSilwal** [Patrick5455/Data-Structures-and-Algorithm-in-Java--Advanced-Concepts#1]
Hi @Patrick5455 , are you currently working on this repository?

Is the goal of this repo jus to list down topics or you have planned to add code over time? I am also working in similar project. Would like to know your ideas.

Thanks

**Comment by Patrick5455** [comment]
Yes I am. The goal is to add codes that covers most part of data strucutres and algorithms in Java. I would be adding codes from the start of the new week.
